<a href="https://colab.research.google.com/github/ShaikMohammadUsman/Machine-Learning/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
import numpy as np


In [85]:
'''   Initializae the 1-d array  '''

a=np.array([1,3,5])   # it is basically a list
a

array([1, 3, 5])

In [86]:
type(a)

numpy.ndarray

In [87]:
 '''   Initializae the 2-d arrays  '''

b=np.array([[1,3,4],[2,5,8]])  # it is basically lists of lists
b

array([[1, 3, 4],
       [2, 5, 8]])

In [88]:
type(b)

numpy.ndarray

In [89]:
'''  To get the dimenions of array  '''

a.ndim

1

In [90]:
b.ndim

2

In [91]:
c=np.array([[[[[1,3,4],[2,5,8]]]]])  # it is basically lists of lists
                                     
c

array([[[[[1, 3, 4],
          [2, 5, 8]]]]])

In [92]:
c.ndim   

5

In [93]:
###   The more the no of  nested lists the more the dimesnsions will be ###

In [94]:
a.dtype

dtype('int64')

In [95]:
type(a)

numpy.ndarray

In [96]:
c.shape

(1, 1, 1, 2, 3)

In [97]:
b.shape

(2, 3)

In [98]:
''' We can specify the dtype while declaring the array '''
d=np.array([2,5,7],dtype='int16')

In [99]:
d.itemsize  # tells us how much memory our integer will take for Each item

2

In [100]:
d.nbytes # tells us how much memory all of our values in the array take .. here 2,5,7 in our array in d.. so it takes 2 * 3 = 6 bytes

6

In [101]:
##  Accessing specific rows and columns etc ./..  

a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

In [102]:
a.ndim

2

In [103]:
a.dtype

dtype('int64')

In [104]:
a.itemsize

8

In [105]:
a.nbytes

112

In [106]:
a.dtype

dtype('int64')

In [107]:
'''   Get an specific eleemnt from an array  '''
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [108]:
'''   Get an specific eleemnt from an array  '''

a[1,1]  # if we want to access 9.. it is in 1st row and 1st column

9

In [109]:
a[1,-6] # using reversing

9

In [110]:
'''  Get a specific Row '''
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [111]:
a[0,:] # if we want 1st row

array([1, 2, 3, 4, 5, 6, 7])

In [112]:
a[:,0] # if we want 1st column

array([1, 8])

In [113]:
a[:,5] # mention whatwe want, if we want column then use column numbaer and dont specify anythng in row

array([ 6, 13])

In [114]:
a[0,1:5]  # if we want eles 2,3,4 thn use this

array([2, 3, 4, 5])

In [115]:
''' modifying the elements '''

' modifying the elements '

In [116]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [117]:
a[0,3]=5

In [118]:
a

array([[ 1,  2,  3,  5,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [119]:
a[:,2]=33  # if we want ot change 2nd column 3,10

In [120]:
a

array([[ 1,  2, 33,  5,  5,  6,  7],
       [ 8,  9, 33, 11, 12, 13, 14]])

In [121]:
# 3-d array

b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [122]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [123]:
b.ndim

3

In [124]:
''' we can get what we want in n-dimensional array '''

b[1,0,0] #mention which set we want first and then which row in that mlist and whcih column in that list, chkfrm the outside

5

In [125]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [126]:
b[:,1,:]=[[2,3],[6,8]]

In [127]:
b

array([[[1, 2],
        [2, 3]],

       [[5, 6],
        [6, 8]]])

In [128]:
''' Iniatialize different types of arrays  '''

np.zeros([1,3]) # mention how many 0's in rows and how many zeros in columns

array([[0., 0., 0.]])

In [129]:
np.ones((2,3,4,2))

array([[[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [130]:
np.full((3,4),fill_value=3,dtype='int16')

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]], dtype=int16)

In [131]:
np.full_like(a,fill_value=8,order='K')

array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

In [132]:
from random import random

In [133]:
np.random.rand(9) # returns the 9 rndom numbers

array([0.0794595 , 0.22406949, 0.32310833, 0.93634477, 0.01281568,
       0.74050098, 0.48864462, 0.17263229, 0.50591583])

In [134]:
np.random.rand(4,5) # returns random numbers with 4 rows and 5 columns

array([[0.50498272, 0.54939252, 0.3393821 , 0.76001974, 0.65552366],
       [0.929118  , 0.92867067, 0.38860777, 0.41594319, 0.65285422],
       [0.50433594, 0.07891479, 0.07277172, 0.49671195, 0.49632706],
       [0.53100203, 0.38994549, 0.22819992, 0.46182885, 0.52506613]])

In [135]:
np.random.randint(1,4,6) #insert 6 random numbers between 1 and 4

array([3, 1, 2, 1, 1, 2])

In [136]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [137]:
f=np.array([[[[[5,5]]]]]) 

In [138]:
f

array([[[[[5, 5]]]]])

In [139]:
f.ndim

5

In [140]:
f[:,0]=[1,1]

In [141]:
f

array([[[[[1, 1]]]]])

In [142]:
f=np.ones((5,5))

In [143]:
f

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [144]:
f[:,1:-1]=0

In [145]:
f[0,:]=1

In [146]:
f

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [147]:
f[:,0]=1

In [148]:
f

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.]])

In [149]:
f[-1,:]=1

In [150]:
f

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [151]:
z=np.zeros([1,3,4]) # this is 3 dimensions   (1 list will b der , 3 rows and 4 columns in that list)

In [152]:
z.ndim # 3 dimensions will be der

3

In [153]:
z

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [154]:
z=np.zeros((1,3,4,6))# if 4th dimension comes then the entire scene changes., the number of columns changes from  4 to 6, apart frm thr everythng remains intact

In [155]:
z.ndim

4

In [156]:
z

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]]])

In [157]:
k=np.zeros([3,3,4,2])# if 4th dimension comes then the entire scene changes., the number of columns changes from  4 to 2, apart frm thr everythng remains intact

In [158]:
k  # you can treat a single list as a row, 2nd list as 2nd row, 3rd list as 3rd row and so on

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [159]:
k.ndim

4

In [160]:
8

8

In [161]:
# we need to be careful while copyiung arrays

import numpy as np
a= np.array([[1,2]])

In [162]:
a.ndim

2

In [163]:
b=a # lets assign a to b

In [164]:
b[0,0]=10 # we cahnged 0th row and 0tth column to 10

In [165]:
b # we can see that b got chnged

array([[10,  2]])

In [166]:
a # but a also changed bcos the value assigned doesnt chnage but the variable change to save memory..so it happened! to avoid that use copy()

array([[10,  2]])

In [167]:
b=a.copy()

In [168]:
b[0,0]=1

In [169]:
b # now only b has chnaged

array([[1, 2]])

In [170]:
a # a has n't chnged bcos we copied a to b

array([[10,  2]])

In [171]:
                                                  '''  Mathematical operations on Numpy  '''

'  Mathematical operations on Numpy  '

In [172]:
a=np.array([1,2,3,4,5]) 

In [173]:
a+2 # addition of array (Adds to every element)

array([3, 4, 5, 6, 7])

In [174]:
a-2 #subtraction of arrays

array([-1,  0,  1,  2,  3])

In [175]:
a*2 # multiplication iof arrays

array([ 2,  4,  6,  8, 10])

In [176]:
  # addition of 2 different arrays

  b=a.copy()
  b

array([1, 2, 3, 4, 5])

In [177]:
a+b

array([ 2,  4,  6,  8, 10])

In [178]:
                              '''  We can do  trignometric operations on arrays too  '''


'  We can do  trignometric operations on arrays too  '

In [179]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [180]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [181]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [182]:
                              '''  We can do  linear algebra operations on arrays too  '''
a= np.ones([2,3])
b=np.full((3,2),2)

In [183]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [184]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [185]:
# find the determinant

c=np.identity(3)

In [186]:
np.linalg.det(c) 

1.0

In [187]:
                                          ''' Statistics  with Numpy '''

' Statistics  with Numpy '

In [188]:
stats=np.array([[1,2,3],[4,5,6]])

In [189]:
stats.ndim

2

In [190]:
stats.min()

1

In [191]:
stats.max()

6

In [192]:
stats.sum()

21

In [193]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [194]:
np.sum(stats,axis=1)

array([ 6, 15])

In [195]:
    ##  reorganizaing arrays (or)  Reshaping arrays ###

before=np.array([[1,2,3,4],[5,6,7,8]])

In [196]:
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [197]:
after=before.reshape((4,2)) # we can reshape any array as per our requuirement

In [198]:
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [200]:
                                              '''  Vertically Stacking the vectors  '''
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
v3=np.vstack([v1,v2,v1,v2])

In [201]:
v3.ndim

2

In [202]:
                                              '''  Horizontally Stacking the vectors  '''


'  Horizontally Stacking the vectors  '

In [203]:
v4=np.hstack((v1,v2))

In [204]:
v4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [205]:
                                                        '''  Miscallaneous  '''


'  Miscallaneous  '

In [208]:
# loading text from data 
file=np.genfromtxt('data.txt',delimiter=',')

OSError: ignored

In [ ]:
# Boolean Masking and Advance Indexing

file.astype('int32')



In [211]:
# we can index with the numpy array #

a=np.array([1,2,3,4,98,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])

In [213]:
np.any(a > 50,axis=0) # chk anyvalue is greater than 50 in 'a' variable

True

In [214]:
np.all(a > 50,axis=0) # chk all the values greater than 50 in 'a' variable

False

In [216]:
a[(a >50) & (a<100)]

array([98])

In [217]:
(a >50) & (a<100)

array([False, False, False, False,  True, False, False, False, False])

In [ ]:
a[2:4,0:2]


In [227]:
i=np.identity(5)

In [228]:
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [229]:
i[0,0]=0

In [230]:
i

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [233]:
j=np.array([[0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 8., 0., 0.],
       [0., 0., 0., 14., 0.],
       [0., 0., 0., 0., 20.]])

In [234]:
k=i*j

In [235]:
k

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  8.,  0.,  0.],
       [ 0.,  0.,  0., 14.,  0.],
       [ 0.,  0.,  0.,  0., 20.]])

In [236]:
# Now how can we select 2,8 in k?

k[[1,2],[1,2]]

array([2., 8.])